
#define CONFIG_DECODERS 1
#define CONFIG_ENCODERS 1
#define CONFIG_RISKY 1
#define HAVE_MALLOC_H 1
#define ENABLE_GRAY 0 

#define ENABLE_MPEGVIDEO_DECODER 1
#define ENABLE_MSMPEG4V1_DECODER 1
#define ENABLE_MSMPEG4V2_DECODER 1
#define ENABLE_MSMPEG4V3_DECODER 1 
#define ENABLE_MPEG4_ENCODER 1
#define ASMALIGN(ZEROBITS) ".align 1<<" #ZEROBITS "\n\t" 
 
#define ENABLE_H263_DECODER 1
#define ENABLE_H263I_DECODER 1
#define ENABLE_H263P_ENCODER 1
#define ENABLE_FLV_DECODER 1
#define ENABLE_RV10_DECODER 1
#define ENABLE_RV20_DECODER 1
#define ENABLE_MPEG4_DECODER 1

#define ENABLE_WMV1_DECODER 1
#define ENABLE_WMV1_ENCODER 1
#define ENABLE_WMV2_ENCODER 1
#define ENABLE_WMV2_DECODER 1

#define ENABLE_MSMPEG4V1_ENCODER 1
#define ENABLE_MSMPEG4V2_ENCODER 1
#define ENABLE_MSMPEG4V3_ENCODER 1

#define ENABLE_H263_ENCODER 1
#define ENABLE_FLV_ENCODER 1
#define ENABLE_RV10_ENCODER 0
#define ENABLE_RV20_ENCODER 0
#define ENABLE_VP3_DECODER 0
#define ENABLE_VP5_DECODER 0
#define ENABLE_VP6_DECODER 0

#define ENABLE_H261_ENCODER 0
#define ENABLE_H261_DECODER 0

#define ENABLE_MJPEG_ENCODER 0
#define ENABLE_LJPEG_ENCODER 0
#define ENABLE_MPEG1VIDEO_ENCODER 1
#define ENABLE_MPEG2VIDEO_ENCODER 1

#define ENABLE_H264_DECODER 1
#define ENABLE_THEORA_DECODER 0
#define ENABLE_MMX 1
#define ENABLE_ARMV4L 0
#define ENABLE_MLIB 0
#define ENABLE_VIS 0
#define ENABLE_ALPHA 0
#define ENABLE_POWERPC 0
#define ENABLE_MMI 0
#define ENABLE_SH4 0
#define ENABLE_BFIN 0

#define ENABLE_THREADS 0
#define ENABLE_SMALL 0

#define CONFIG_WMV2_DECODER 1
#define CONFIG_WMV2_ENCODER 1

//#define HAVE_MKSTEMP 1 

#undef  HAVE_MEMALIGN
#ifndef M_PI
 #define M_PI 3.14159265358979323846
#endif
